### ISSUE TITLE
Issue with depth model 

### ISSUE THREAD

**Issue by mitchellhart** [amithgc/DeforumStableDiffusion-v0.5-Local#1]
The script is crashing while trying to download the depth model (dpt_large-midas-2f21e586.pt)

I have this file in the ./models folder

console error:
> Downloading dpt_large-midas-2f21e586.pt...
Traceback (most recent call last):
  File "run.py", line 1710, in <module>
    main()
  File "run.py", line 1659, in main
    render_animation(args, anim_args)
  File "run.py", line 1307, in render_animation
    depth_model.load_midas(models_path)
  File "stable-diffusion\helpers\depth.py", line 38, in load_midas
    wget("https://github.com/intel-isl/DPT/releases/download/1_0/dpt_large-midas-2f21e586.pt", models_path)
  File "stable-diffusion\helpers\depth.py", line 16, in wget
    print(subprocess.run(['wget', url, '-P', outputdir], stdout=subprocess.PIPE).stdout.decode('utf-8'))
  File "C:\Users\Miner3\.conda\envs\dsdv0.5\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Miner3\.conda\envs\dsdv0.5\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Miner3\.conda\envs\dsdv0.5\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by amithgc** [comment]
Can u provide me ur settings json

**Comment by mitchellhart** [comment]
Sure - apologize it's just pasted in, I can't upload the .json here


{
    "batch_name": "forest",
    "W": 768,
    "H": 448,
    "restore_faces": false,
    "tiling": false,
    "enable_hr": true,
    "firstphase_width": 0,
    "firstphase_height": 0,
    "seed": 3814351474,
    "sampler": "klms",
    "seed_enable_extras": false,
    "subseed": -1,
    "subseed_strength": 0,
    "seed_resize_from_w": 0,
    "seed_resize_from_h": 0,
    "steps": 60,
    "ddim_eta": 0.0,
    "n_batch": 1,
    "make_grid": false,
    "grid_rows": 1,
    "save_settings": true,
    "save_samples": true,
    "display_samples": false,
    "save_sample_per_step": false,
    "show_sample_per_step": false,
    "override_these_with_webui": false,
    "filename_format": "{timestring}_{index}_{prompt}.png",
    "seed_behavior": "iter",
    "use_init": false,
    "from_img2img_instead_of_link": false,
    "strength_0_no_init": true,
    "strength": 0,
    "init_image": null,
    "use_mask": false,
    "use_alpha_as_mask": false,
    "invert_mask": false,
    "overlay_mask": false,
    "mask_file": "",
    "mask_contrast_adjust": 1.0,
    "mask_brightness_adjust": 1.0,
    "mask_overlay_blur": 5.0,
    "precision": "autocast",
    "scale": 7,
    "C": 4,
    "f": 8,
    "prompt": "",
    "timestring": "",
    "init_latent": null,
    "init_sample": null,
    "init_c": null,
    "prompts": {
        "0": "variety of plant specimens.",
        "90": "molecules and science charts and diagrams."
    },
    "animation_mode": "3D",
    "max_frames": 100,
    "border": "replicate",
    "angle": "0:(0)",
    "zoom": "0:(0)",
    "translation_x": "0:(0)",
    "translation_y": "0:(0)",
    "translation_z": "0:(1.02+0.01*sin(1.14*t/30))",
    "rotation_3d_x": "0:(0)",
    "rotation_3d_y": "0:(0)",
    "rotation_3d_z": "0:(0)",
    "flip_2d_perspective": false,
    "perspective_flip_theta": "0:(0)",
    "perspective_flip_phi": "0:(t%15)",
    "perspective_flip_gamma": "0:(0)",
    "perspective_flip_fv": "0:(53)",
    "noise_schedule": "0:(0)",
    "strength_schedule": "0: (0.7)",
    "contrast_schedule": "0: (1.0)",
    "cfg_scale_schedule": "0: (7)",
    "fov_schedule": "0: (40)",
    "near_schedule": "0: (200)",
    "far_schedule": "0: (10000)",
    "seed_schedule": "0: (t%4294967293)",
    "color_coherence": "Match Frame 0 LAB",
    "diffusion_cadence": 3,
    "use_depth_warping": true,
    "midas_weight": 0.3,
    "near_plane": 200.0,
    "far_plane": 10000.0,
    "fov": 40.0,
    "padding_mode": "border",
    "sampling_mode": "bicubic",
    "save_depth_maps": false,
    "video_init_path": "/content/video_in.mp4",
    "extract_nth_frame": 1,
    "overwrite_extracted_frames": false,
    "use_mask_video": false,
    "video_mask_path": "/content/video_in.mp4",
    "interpolate_key_frames": false,
    "interpolate_x_frames": 4,
    "resume_from_timestring": false,
    "resume_timestring": "20220829210106"
}
